#!/usr/bin/ruby -w

# McFly - McRouter Reliable Delete Stream Replay

$:.unshift File.dirname(__FILE__)
require('lib/mcfly')

path = ARGV.first

config = McFlyConfig.new path

mcfly = McFly.new config

mcfly.run
